<a href="https://colab.research.google.com/github/MatthewBabajide/FirstColab/blob/master/Numpy_Arrays_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

print(type(np_height))

<class 'numpy.ndarray'>


In [ ]:
# Calculate bmi
bmi = np_weight / np_height ** 2

# Print the result
print(bmi)

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


In [ ]:
# For a boolean response
bmi > 25

# Print only those observations above 23
bmi[bmi > 25]

array([27.88755755, 28.75558507, 25.48723993, 25.84368152])

In [ ]:
dict = {"country": ["Brazil", "Russia", "India", "China", "South Africa"],
       "capital": ["Brasilia", "Moscow", "New Dehli", "Beijing", "Pretoria"],
       "area": [8.516, 17.10, 3.286, 9.597, 1.221],
       "population": [200.4, 143.5, 1252, 1357, 52.98] }

import pandas as pd
brics = pd.DataFrame(dict)
print(brics)

        country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Dehli   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98


In [ ]:
# Set the index for brics
brics.index = ["BR", "RU", "IN", "CH", "SA"]

# Print out brics with new index values
print(brics)

         country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Dehli   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98


In [ ]:
arr = [3,4,5,6]
print (type(arr))

<class 'list'>


In [ ]:
from numpy import random

#this is to generate a random number from the "choice" and the probabilities of each choice given below
x = random.choice([1, 2, 3, 4, 5, 6], p=[0.18, 0.18, 0.18, 0.18, 0.18, 0.1], size=(20))

print(x)

[3 1 3 1 1 2 1 1 2 2 3 5 5 4 4 2 5 4 3 3]


In [ ]:
!pip install seaborn

In [ ]:
print (np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

a = np.zeros((2,3))
print (a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

a = np.ones((2,3))
print (a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np

a = np.full((2, 3), [1, 0 ,1])
print (a)

[[1 0 1]
 [1 0 1]]


In [ ]:
import numpy as np

a = np.identity(3)
print (a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Fibonacci sequence

x, y= 0, 1
fib_seq = [x, y]

while (y < 21):
    x, y= y, x+y
    fib_seq.append(y)
    
    
print (fib_seq)
    


[0, 1, 1, 2, 3, 5, 8, 13, 21]


In [ ]:
print (np.random.randn(10, 2, 3))

[[[ 1.64078637  1.68765496  1.56330805]
  [-0.82014433 -0.0325888  -1.19418049]]

 [[ 2.32472689 -1.40087598 -2.37913018]
  [ 0.25047392  1.88341311 -0.51251027]]

 [[ 0.60840086 -0.52406335  0.82261586]
  [ 0.86971644 -0.46374137 -0.50257122]]

 [[ 1.13191017 -0.99802875  1.05236713]
  [-0.39231046 -1.20835509  1.21342173]]

 [[ 0.67254676 -0.74206855 -0.01429169]
  [ 1.00423145  0.14300924  0.18735805]]

 [[ 1.13191383 -0.2627261  -2.0037709 ]
  [-0.08836205  0.31622875 -0.11084574]]

 [[-2.97212651  0.67966705  0.19423749]
  [ 0.10867098  0.31912498 -1.47050476]]

 [[ 0.48045035 -1.51551661  1.73905538]
  [-1.27716072  0.08900974  1.90238253]]

 [[-0.14966738 -0.99159106  1.26999643]
  [-0.54415037  0.02869158  0.44296501]]

 [[ 1.437573   -2.27937114  1.02993865]
  [ 0.96551116 -1.29412788 -0.69555757]]]


In [ ]:
print (np.random.random(10))

[0.74691263 0.74729891 0.91735302 0.05076807 0.2982497  0.42798949
 0.17382339 0.78290545 0.63233906 0.94649509]


In [ ]:
import pandas as pd

d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(d)
df

col1  col2
0     1     3
1     2     4

In [ ]:
dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))

df

A         B         C         D
2013-01-01 -0.330839  0.487052 -0.277278 -0.017894
2013-01-02 -0.500477 -1.919782  1.429431  0.034463
2013-01-03  0.200398  0.556380  0.392993  0.053628
2013-01-04  0.797396  1.640725 -0.507971 -0.117631
2013-01-05  0.694327 -0.631434 -0.606401 -0.061020
2013-01-06 -0.356058  0.828836  0.150624 -0.722275

In [ ]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
a = np.array(["2",3, 4])

a

array(['2', '3', '4'], dtype='<U1')

In [ ]:
import pandas as pd

dfdates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))

df


A         B         C         D
2013-01-01  0.373145  1.921036  0.323088  2.334697
2013-01-02 -0.043298 -0.122025  0.842979  0.524303
2013-01-03 -0.532161  1.465240  1.860939 -0.614883
2013-01-04 -0.186889 -0.097844  0.295218  0.663471
2013-01-05 -1.279110 -1.716260 -0.149833  1.465214
2013-01-06  0.156695 -0.879946  1.839508 -0.521941

In [ ]:
df.sort_index(axis=0, ascending=False)

A         B         C         D
2013-01-06  0.156695 -0.879946  1.839508 -0.521941
2013-01-05 -1.279110 -1.716260 -0.149833  1.465214
2013-01-04 -0.186889 -0.097844  0.295218  0.663471
2013-01-03 -0.532161  1.465240  1.860939 -0.614883
2013-01-02 -0.043298 -0.122025  0.842979  0.524303
2013-01-01  0.373145  1.921036  0.323088  2.334697

In [ ]:
df2 = df.copy()

df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three']

df2

A         B         C         D      E
2013-01-01  0.373145  1.921036  0.323088  2.334697    one
2013-01-02 -0.043298 -0.122025  0.842979  0.524303    one
2013-01-03 -0.532161  1.465240  1.860939 -0.614883    two
2013-01-04 -0.186889 -0.097844  0.295218  0.663471  three
2013-01-05 -1.279110 -1.716260 -0.149833  1.465214   four
2013-01-06  0.156695 -0.879946  1.839508 -0.521941  three

In [ ]:
s= pd.Series(["Food", "Music", "Clothes", "Watches"])
s

0       Food
1      Music
2    Clothes
3    Watches
dtype: object

In [ ]:
df = pd.DataFrame(np.random.randn(3,4), columns = s)

In [ ]:
df

Food     Music   Clothes   Watches
0  1.369703 -1.068670  0.371120 -0.730377
1  0.662565  0.391807 -1.774878 -0.824161
2 -0.694242  0.328310 -0.037339 -0.070464

In [ ]:
df["Food"] = ["Yam and Eggs", "Eba and Oha Soup", "Fried Plaantain"]
df

Food     Music   Clothes   Watches
0      Yam and Eggs -1.068670  0.371120 -0.730377
1  Eba and Oha Soup  0.391807 -1.774878 -0.824161
2   Fried Plaantain  0.328310 -0.037339 -0.070464

In [ ]:
df["Shoes"] = ["Addidas", "Hightops", "Red bottoms"]
df

Food     Music   Clothes   Watches        Shoes
0      Yam and Eggs -1.068670  0.371120 -0.730377      Addidas
1  Eba and Oha Soup  0.391807 -1.774878 -0.824161     Hightops
2   Fried Plaantain  0.328310 -0.037339 -0.070464  Red bottoms

In [ ]:
df["Watches"] = ["Tissot", "Swatch", np.nan]
df

Food     Music   Clothes Watches        Shoes
0      Yam and Eggs -1.068670  0.371120  Tissot      Addidas
1  Eba and Oha Soup  0.391807 -1.774878  Swatch     Hightops
2   Fried Plaantain  0.328310 -0.037339     NaN  Red bottoms

In [ ]:
df.columns

Index(['Food', 'Music', 'Clothes', 'Watches', 'Shoes'], dtype='object')

In [ ]:
df.describe()

Music   Clothes
count  3.000000  3.000000
mean  -0.116185 -0.480366
std    0.825488  1.139531
min   -1.068670 -1.774878
25%   -0.370180 -0.906108
50%    0.328310 -0.037339
75%    0.360058  0.166891
max    0.391807  0.371120

In [ ]:
df.sort_values(by = "Music")

Food     Music   Clothes Watches        Shoes
0      Yam and Eggs -1.068670  0.371120  Tissot      Addidas
2   Fried Plaantain  0.328310 -0.037339     NaN  Red bottoms
1  Eba and Oha Soup  0.391807 -1.774878  Swatch     Hightops

In [ ]:
 df.loc[1]

Food       Eba and Oha Soup
Music              0.391807
Clothes            -1.77488
Watches              Swatch
Shoes              Hightops
Name: 1, dtype: object

In [ ]:
df.loc[: , ["Food", "Shoes"]]

Food        Shoes
0      Yam and Eggs      Addidas
1  Eba and Oha Soup     Hightops
2   Fried Plaantain  Red bottoms

In [ ]:
df.loc[0, "Food"]

'Yam and Eggs'

In [ ]:
df.iloc[0,3]

'Tissot'

In [ ]:
df.loc[:, "Music"]=np.array([5.]*len(df))

In [ ]:
df

Food  Music   Clothes Watches        Shoes
0      Yam and Eggs    5.0  0.371120  Tissot      Addidas
1  Eba and Oha Soup    5.0 -1.774878  Swatch     Hightops
2   Fried Plaantain    5.0 -0.037339     NaN  Red bottoms

In [ ]:
df1 = df.reindex([1,2,3], fill_value = "any")

In [ ]:
df1 


Food Music    Clothes Watches        Shoes
1  Eba and Oha Soup     5   -1.77488  Swatch     Hightops
2   Fried Plaantain     5 -0.0373389     NaN  Red bottoms
3               any   any        any     any          any

In [ ]:
df1.fillna(4)

df1


Food Music    Clothes Watches        Shoes
1  Eba and Oha Soup     5   -1.77488  Swatch     Hightops
2   Fried Plaantain     5 -0.0373389     NaN  Red bottoms
3               any   any        any     any          any

In [ ]:
df1.fillna(4)

df1


Food Music    Clothes Watches        Shoes
1  Eba and Oha Soup     5   -1.77488  Swatch     Hightops
2   Fried Plaantain     5 -0.0373389     NaN  Red bottoms
3               any   any        any     any          any

In [ ]:
df.fillna("Yooo")
df

Food  Music   Clothes Watches        Shoes
0      Yam and Eggs    5.0  0.371120  Tissot      Addidas
1  Eba and Oha Soup    5.0 -1.774878  Swatch     Hightops
2   Fried Plaantain    5.0 -0.037339     NaN  Red bottoms

In [ ]:
df = pd.DataFrame([('bird', 'Falconiformes', 389.0),
                   ('bird', 'Psittaciformes', 24.0),
                   ('mammal', 'Carnivora', 80.2),
                   ('mammal', 'Primates', np.nan),
                   ('mammal', 'Carnivora', 58)],
                    index=['falcon', 'parrot', 'lion', 'monkey', 'leopard'],
                    columns=('class', 'order', 'max_speed'))
df

class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [ ]:
grouped = df.groupby('class')

In [ ]:
df

class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [ ]:
grouped = df.groupby('order', axis='columns')

In [ ]:
grouped

In [ ]:
grouped = df.groupby(['class', 'order'])
grouped

In [ ]:
df

class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [ ]:
df.groupby("order")

In [ ]:
rng = pd.date_range('1/1/2012', periods=100, freq='S')
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)
ts

2012-01-01 00:00:00    377
2012-01-01 00:00:01    136
2012-01-01 00:00:02    335
2012-01-01 00:00:03    274
2012-01-01 00:00:04    215
                      ... 
2012-01-01 00:01:35    249
2012-01-01 00:01:36     19
2012-01-01 00:01:37     60
2012-01-01 00:01:38    463
2012-01-01 00:01:39    259
Freq: S, Length: 100, dtype: int32

In [ ]:
ts.resample('5Min').sum()

2012-01-01    23728
Freq: 5T, dtype: int32